[package]
name = "btc-api-rust"
version = "0.1.0"
authors = ["npodonnell <6617714+npodonnell@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
